package com.getpcpanel.rest;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.TreeSet;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.getpcpanel.AppLikeMapper;

/**
 * quarkus-rest-jackson can generate a build-time reader per DTO instead of going through reflection.
 * Those readers discover properties from <em>backing fields</em>, so a property carried by a
 * getter/setter pair alone is absent from the generated reader and — with
 * {@code quarkus.jackson.fail-on-unknown-properties=false} — dropped from the document without a
 * word. For the DTOs below that document is the user's save file, so a drop is a setting lost on load
 * and written back absent on the next save.
 *
 * <p>Nothing else catches this. Every mapper in the test suite, {@link AppLikeMapper} included, is a
 * plain {@link ObjectMapper} that reads such a property correctly, and a {@code @QuarkusTest} (the
 * only thing holding the real mapper) cannot run here — see {@link AppLikeMapper}'s note on device
 * providers scanning real hardware at startup.
 *
 * <p>So this pins the pair that has to hold: either the generated readers are off, or no contract DTO
 * carries a writable property without a field for the generator to find.
 */
@DisplayName("Generated Jackson readers cannot silently drop a fieldless property")
class GeneratedJacksonReaderHazardTest {
    private static final String KEY = "quarkus.rest.jackson.optimization.enable-reflection-free-serializers";

    @Test
    @DisplayName("no contract DTO relies on a property the generated reader would not see")
    void noFieldlessWritablePropertyOnContractDtos() {
        var generatedReadersEnabled = !"false".equals(properties().getProperty(KEY, "true").trim());
        var hazards = fieldlessWritableProperties();

        if (generatedReadersEnabled && !hazards.isEmpty()) {
            fail("""
                    These properties have a setter but no backing field, so the build-time reader \
                    generated by quarkus-rest-jackson leaves them out and reading one is a silent \
                    no-op: %s
                    Give each a backing field, or set %s=false in application.properties.""".formatted(hazards, KEY));
        }
    }

    @Test
    @DisplayName("the scan reaches the DTOs it is meant to cover")
    void theScanIsNotVacuous() {
        var scanned = AppLikeMapper.scanProjectClasses().stream().filter(GeneratedJacksonReaderHazardTest::isContractDto).count();
        assertTrue(scanned > 20, "Suspiciously few contract DTOs scanned: " + scanned);
    }

    private static TreeSet<String> fieldlessWritableProperties() {
        var mapper = new ObjectMapper();
        var config = mapper.getDeserializationConfig();
        var found = new TreeSet<String>();
        for (var clazz : AppLikeMapper.scanProjectClasses()) {
            if (!isContractDto(clazz)) {
                continue;
            }
            try {
                for (var property : config.introspect(config.constructType(clazz)).findProperties()) {
                    if (property.hasSetter() && !property.hasField()) {
                        found.add(clazz.getSimpleName() + "." + property.getName());
                    }
                }
            } catch (RuntimeException e) { // not a bean Jackson can describe; nothing to generate for it either
            }
        }
        return found;
    }

    /** The JSON contract surface: the save-file graph and the REST DTOs, the same shape the TS generator takes. */
    private static boolean isContractDto(Class<?> clazz) {
        if (clazz.isInterface() || clazz.isEnum() || clazz.isAnonymousClass() || clazz.isSynthetic()) {
            return false;
        }
        var name = clazz.getName();
        return name.contains(".dto.") && !name.contains("$");
    }

    private static Properties properties() {
        var path = Path.of(System.getProperty("user.dir")).resolve("src/main/resources/application.properties");
        var properties = new Properties();
        try (var in = Files.newInputStream(path)) {
            properties.load(in);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot read " + path, e);
        }
        return properties;
    }
}
