/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getpcpanel_cpp_SndCtrlNative */

#ifndef _Included_com_getpcpanel_cpp_SndCtrlNative
#define _Included_com_getpcpanel_cpp_SndCtrlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_getpcpanel_cpp_SndCtrlNative
 * Method:    start
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrlNative_start
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_getpcpanel_cpp_SndCtrlNative
 * Method:    setDeviceVolume
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrlNative_setDeviceVolume
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_getpcpanel_cpp_SndCtrlNative
 * Method:    setProcessVolume
 * Signature: (Ljava/lang/String;IF)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrlNative_setProcessVolume
  (JNIEnv *, jobject, jstring, jint, jfloat);

/*
 * Class:     com_getpcpanel_cpp_SndCtrlNative
 * Method:    setFocusVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrlNative_setFocusVolume
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
