/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getpcpanel_cpp_windows_SndCtrlNative */

#ifndef _Included_com_getpcpanel_cpp_windows_SndCtrlNative
#define _Included_com_getpcpanel_cpp_windows_SndCtrlNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    start
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_start
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    setDeviceVolume
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_setDeviceVolume
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    setProcessVolume
 * Signature: (Ljava/lang/String;IF)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_setProcessVolume
  (JNIEnv *, jobject, jstring, jint, jfloat);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    setFocusVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_setFocusVolume
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    setDefaultDevice
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_setDefaultDevice
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    muteDevice
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_muteDevice
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    muteSession
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_muteSession
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    getFocusApplication
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_getFocusApplication
  (JNIEnv *, jobject);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    setPersistedDefaultAudioEndpoint
 * Signature: (IILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_setPersistedDefaultAudioEndpoint
(JNIEnv*, jobject, jint, jint, jstring);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    getPersistedDefaultAudioEndpoint
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_getPersistedDefaultAudioEndpoint
(JNIEnv*, jobject, jint, jint);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    hasAudioPolicyConfigFactory
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_hasAudioPolicyConfigFactory
(JNIEnv*, jobject);

/*
 * Class:     com_getpcpanel_cpp_windows_SndCtrlNative
 * Method:    triggerAv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_windows_SndCtrlNative_triggerAv
(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
