/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getpcpanel_cpp_SndCtrl */

#ifndef _Included_com_getpcpanel_cpp_SndCtrl
#define _Included_com_getpcpanel_cpp_SndCtrl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_getpcpanel_cpp_SndCtrl
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrl_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_getpcpanel_cpp_SndCtrl
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_getpcpanel_cpp_SndCtrl_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
